### ISSUE TITLE
Gherkin-style prefix also detected halfway in the keyword

### ISSUE THREAD

**Issue by itavero** [wingyplus/language-robot-framework#12]
In the example below **But**ton will be highlighted as well as **And**. As far as I can tell it only makes sense to highlight these words when the are the start of a keyword.

``` robot
*** Test Cases ***
Some Example Case
    Press And Hold The Button
```

**Comment by wingyplus** [comment]
From spec http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#behavior-driven-style , It not make any sense to highlight **But**ton.

**Comment by itavero** [comment]
I know it does not make any sense, but this is what is currently happening. So I reckon this bug should be fixed.

**Comment by wingyplus** [comment]
If it's bug please tell me what theme do you use and please capture your screen to confirm this bug.

Thanks

**Comment by itavero** [comment]
I updated to v1.0.0 of this package this morning and I no longer see this behavior. Can it be that it was fixed already?

**Comment by wingyplus** [comment]
I added test to cover this scenario for prevent it happen again. 

Thanks for your contribution.
