### ISSUE TITLE
Highlight kwargs

### ISSUE THREAD

**Issue by itavero** [wingyplus/language-robot-framework#13]
Currently only regular arguments (`${arg}`) and varargs/lists (`@{arg}`) are highlighted, but kwargs (`&{arg}`) are not. Also see the [Robot Framework User Guide on "Kwargs with user keywords"](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#kwargs-with-user-keywords).

Example:

``` robot
*** Keywords ***
Some Example Keyword
    [Arguments]   ${regular_arg}   &{others_as_kwarg}
    Some Other Keyword    &{others_as_kwarg}
```

**Comment by wingyplus** [comment]
Thanks for propose idea. I will implement it soon.
