### ISSUE TITLE
Run pybot from menus

### ISSUE THREAD

**Issue by wingyplus** [wingyplus/language-robot-framework#5]

**Comment by just-be-dev** [comment]
So I created a project [atom-robotframework](https://github.com/zephraph/atom-robotframework) that I hope to make into a robot framework helper. It should cover this issue, #4, and #2. It's just starting, but I'd be happy to have you help with it.

**Comment by wingyplus** [comment]
I will be add after [atom-robotframework](https://github.com/zephraph/atom-robotframework) release.

Thanks :)

**Comment by molsky** [comment]
By the way, with RF version 3.0 and later things goes a little more complicated.

> New generic robot start-up script has been introduced to allow running tests like robot tests.robot regardless the Python interpreter (#2216). Old interpreter specific pybot, jybot and ipybot scripts still work as earlier, but the plan is to deprecate and remove them in the future major releases.
