### ISSUE TITLE
Grammar should only show comment if '#' symbol first character

### ISSUE THREAD

**Issue by just-be-dev** [wingyplus/language-robot-framework#7]
RF allows for `#` characters to be used within a cell and the cell not be considered a comment. It's only a comment if it's the first symbol in the cell. 

> When Robot Framework parses the test data, it ignores:
> - ...
> - All characters following the hash character (#), when it is the first character of a cell. This means that hash marks can be used to enter comments in the test data.

[source](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#rules-for-parsing-the-data)

**Comment by wingyplus** [comment]
@zephraph thanks for reported the bug. I fix it in version 0.6.0 now.
