### ISSUE TITLE
Run rflint automatically on save.

### ISSUE THREAD

**Issue by wingyplus** [wingyplus/language-robot-framework#9]
[rflint](https://github.com/boakley/robotframework-lint) is a tool for lint robot framework file. I want to show description about linting result like image below.

![screen shot 2558-05-10 at 11 47 44 pm](https://cloud.githubusercontent.com/assets/484530/7555259/83c9d59e-f76f-11e4-8995-9768997e4f95.png)

Acceptance criteria:
- [ ] show yellow text when rflint show result with `W` at first character.
- [ ] show red text when rflint show result with `E` at first character.
- [ ] show line number of lint result.

**Comment by just-be-dev** [comment]
You probably shouldn't make this a part of the language package.

Instead it should most likely be made into a separate linter-robotframework package and use the linter service.

**Comment by wingyplus** [comment]
@zephraph Thanks you for your suggestion. I will extract it from language package soon. 

Thanks.
